### ISSUE TITLE
Upgrade `ssh` to `1.8.0`.

### ISSUE THREAD

**Issue by WeeJeWel** [apocas/docker-modem#141]
Fixes this issue: https://github.com/mscdex/ssh2/issues/1083#issuecomment-1077824328

**Comment by sigilworks** [comment]
@apocas I think @WeeJeWel here is referring to [`ssh2`](https://www.npmjs.com/package/ssh2) (now at `1.10.0`). 

This problem that is fixed in the PR WeeJeWel mentions below fixes issues we're having with M1 Mac users (and some Windows WSL2 users) installing projects using `dockerode`.  Would be great to have this dependency bumped if possible.

**Comment by apocas** [comment]
SSH2 bumped and published on docker-modem v3.0.6

**Comment by WeeJeWel** [comment]
Thank you!
